//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string accountID { get; set; }
        public string accountPassword { get; set; }
        public string accountFirstName { get; set; }
        public string accountLastName { get; set; }
        public string accountEmail { get; set; }
        public string accountPhone { get; set; }
        public string accountAddress { get; set; }
    }
}
